In [2]:
# Libraries importations :
import numpy as np 
import pandas as pd

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from tqdm import tqdm
tqdm.pandas()

import warnings
warnings.filterwarnings("ignore")
import gc

from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder

import optuna

import xgboost as xgb
import lightgbm as lgb
import catboost as cb

bold = ['\033[1m', '\033[0m']

# Read files
path = '/kaggle/input/playground-series-s3e1/'
train = pd.read_csv(path+'train.csv')
test = pd.read_csv(path+'test.csv')
ss = pd.read_csv(path+'sample_submission.csv')

from sklearn.datasets import fetch_california_housing as fch
sklearn_df = pd.DataFrame(fch()['data'], columns=fch()['feature_names'])
sklearn_df['MedHouseVal'] = fch()['target']

# Show all columns
pd.set_option('display.max_columns', None)

---

# | Preprocessing

---

## || Generated Data

In [3]:
sklearn_df['is_generated'] = 0
train['is_generated'] = 1
test['is_generated'] = 1

train.drop('id', axis=1, inplace=True)
train = pd.concat([train, sklearn_df], 
                  ignore_index=True)
test.drop('id', axis=1, inplace=True)

train.loc[33228,['Latitude','Longitude']] = [32.74, -117]
train.loc[34363,['Latitude','Longitude']] = [32.71, -117]
train.loc[20991,['Latitude','Longitude']] = [34.2, -119]

df = pd.concat([train, test], axis=0, ignore_index=True)

## || Encoding trick

In [4]:
emb_size = 20
precision = 1e6 

latlon = np.expand_dims(df[['Latitude', 'Longitude']].values, axis=-1) 

m = np.exp(np.log(precision) / emb_size) 
angle_freq = m ** np.arange(emb_size) 
angle_freq = angle_freq.reshape(1, 1, emb_size) 

latlon = latlon * angle_freq  # Frequence de corrélation angulatoires triangulées
latlon[..., 0::2] = np.cos(latlon[..., 0::2]) 
latlon[..., 1::2] = np.sin(latlon[..., 1::2]) 
latlon = latlon.reshape(-1, 2 * emb_size)

In [5]:
df['exp_latlon1'] = [lat[0] for lat in latlon]
df['exp_latlon2'] = [lat[1] for lat in latlon]

In [6]:
from sklearn.decomposition import PCA

coordinates = df[['Latitude', 'Longitude']].values
pca = PCA().fit(coordinates)
df['pca_lat'] = pca.transform(coordinates)[:,0]
df['pca_lon'] = pca.transform(coordinates)[:,1]

In [7]:
%%time

from umap import UMAP
umap = UMAP(n_components=2, n_neighbors=50, random_state=228).fit(coordinates)
df['umap_lat'] = umap.transform(coordinates)[:,0]
df['umap_lon'] = umap.transform(coordinates)[:,1]

CPU times: user 13min 35s, sys: 2min 42s, total: 16min 18s
Wall time: 8min 13s

---

# Pycaret anomaly /ToDo : Try to plot UMAP

In [51]:
pip install pycaret

Collecting pycaret
  Downloading pycaret-2.3.10-py3-none-any.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.2/320.2 kB 548.9 kB/s eta 0:00:0000:0100:01
Requirement already satisfied: pandas-profiling>=2.8.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.1.0)
Requirement already satisfied: wordcloud in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.8.2.2)
Requirement already satisfied: pyLDAvis in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.2.2)
Requirement already satisfied: umap-learn in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.5.3)
Collecting pyod
  Downloading pyod-1.0.7.tar.gz (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.7/147.7 kB 3.0 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Collecting scipy<=1.5.4
  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.9/25.9 MB 13.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scikit-plot in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.3.7)
Requirement already satisfied: cufflinks>=0.17.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.17.3)
Collecting gensim<4.0.0
  Downloading gensim-3.8.3-cp37-cp37m-manylinux1_x86_64.whl (24.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 13.7 MB/s eta 0:00:0000:0100:01
Collecting spacy<2.4.0
  Downloading spacy-2.3.9-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 20.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: yellowbrick>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.5)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.5.3)
Collecting pyyaml<6.0.0
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 636.6/636.6 kB 37.5 MB/s eta 0:00:00
Requirement already satisfied: mlxtend>=0.17.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.21.0)
Requirement already satisfied: joblib in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.0.1)
Requirement already satisfied: Boruta in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.3)
Requirement already satisfied: plotly>=4.4.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (5.11.0)
Requirement already satisfied: nltk in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.8.1)
Collecting numba<0.55
  Downloading numba-0.54.1-cp37-cp37m-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 16.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: textblob in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.17.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.3.5)
Requirement already satisfied: IPython in /opt/conda/lib/python3.7/site-packages (from pycaret) (7.33.0)
Collecting imbalanced-learn==0.7.0
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 15.7 MB/s eta 0:00:00
Requirement already satisfied: seaborn in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.11.2)
Collecting scikit-learn==0.23.2
  Downloading scikit_learn-0.23.2-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 17.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: ipywidgets in /opt/conda/lib/python3.7/site-packages (from pycaret) (7.7.1)
Collecting mlflow
  Downloading mlflow-1.30.0-py3-none-any.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 15.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: kmodes>=0.10.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.12.2)
Requirement already satisfied: lightgbm>=2.3.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.3.2)
Requirement already satisfied: numpy>=1.13.3 in /opt/conda/lib/python3.7/site-packages (from imbalanced-learn==0.7.0->pycaret) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from scikit-learn==0.23.2->pycaret) (3.1.0)
Requirement already satisfied: setuptools>=34.4.1 in /opt/conda/lib/python3.7/site-packages (from cufflinks>=0.17.0->pycaret) (59.8.0)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.7/site-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: colorlover>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: smart-open>=1.8.1 in /opt/conda/lib/python3.7/site-packages (from gensim<4.0.0->pycaret) (6.3.0)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (0.18.1)
Requirement already satisfied: backcall in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (0.2.0)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (5.3.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (5.1.1)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (4.8.0)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (0.1.3)
Requirement already satisfied: pygments in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (2.12.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from IPython->pycaret) (3.0.30)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets->pycaret) (3.6.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets->pycaret) (6.15.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets->pycaret) (1.1.1)
Requirement already satisfied: wheel in /opt/conda/lib/python3.7/site-packages (from lightgbm>=2.3.1->pycaret) (0.37.1)
Collecting mlxtend>=0.17.0
  Downloading mlxtend-0.20.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 44.6 MB/s eta 0:00:00
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 41.6 MB/s eta 0:00:00
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (1.4.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (9.1.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (4.33.3)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pycaret) (22.0)
Collecting numpy>=1.13.3
  Downloading numpy-1.20.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 15.9 MB/s eta 0:00:0000:0100:01
Collecting llvmlite<0.38,>=0.37.0rc1
  Downloading llvmlite-0.37.0-cp37-cp37m-manylinux2014_x86_64.whl (26.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.3/26.3 MB 14.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas->pycaret) (2022.1)
Requirement already satisfied: tangled-up-in-unicode==0.1.0 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (0.1.0)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (0.7.4)
Requirement already satisfied: missingno>=0.4.2 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (0.4.2)
Requirement already satisfied: phik>=0.11.1 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (0.12.2)
Collecting markupsafe~=2.0.1
  Downloading MarkupSafe-2.0.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (31 kB)
Requirement already satisfied: requests>=2.24.0 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (2.28.1)
Requirement already satisfied: tqdm>=4.48.2 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (4.64.0)
Requirement already satisfied: jinja2>=2.11.1 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (3.1.2)
Requirement already satisfied: multimethod>=1.4 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (1.4)
Requirement already satisfied: pydantic>=1.8.1 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (1.8.2)
Requirement already satisfied: htmlmin>=0.1.12 in /opt/conda/lib/python3.7/site-packages (from pandas-profiling>=2.8.0->pycaret) (0.1.12)
Requirement already satisfied: attrs>=19.3.0 in /opt/conda/lib/python3.7/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (21.4.0)
Requirement already satisfied: networkx>=2.4 in /opt/conda/lib/python3.7/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (2.5)
Requirement already satisfied: imagehash in /opt/conda/lib/python3.7/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (4.2.1)
Requirement already satisfied: tenacity>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from plotly>=4.4.1->pycaret) (8.0.1)
Collecting plac<1.2.0,>=0.9.6
  Downloading plac-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /opt/conda/lib/python3.7/site-packages (from spacy<2.4.0->pycaret) (0.7.9)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from spacy<2.4.0->pycaret) (3.0.8)
Collecting thinc<7.5.0,>=7.4.1
  Downloading thinc-7.4.6-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 42.2 MB/s eta 0:00:00
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/conda/lib/python3.7/site-packages (from spacy<2.4.0->pycaret) (1.0.9)
Collecting catalogue<1.1.0,>=0.0.7
  Downloading catalogue-1.0.2-py2.py3-none-any.whl (16 kB)
Collecting srsly<1.1.0,>=1.0.2
  Downloading srsly-1.0.6-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (208 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.6/208.6 kB 19.1 MB/s eta 0:00:00
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /opt/conda/lib/python3.7/site-packages (from spacy<2.4.0->pycaret) (0.10.1)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from spacy<2.4.0->pycaret) (2.0.7)
Collecting yellowbrick>=1.0.1
  Downloading yellowbrick-1.4-py3-none-any.whl (274 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.2/274.2 kB 23.7 MB/s eta 0:00:00
  Downloading yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 271.4/271.4 kB 21.1 MB/s eta 0:00:00
Collecting numpy>=1.13.3
  Downloading numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 16.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: sqlparse<1,>=0.4.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (0.4.2)
Requirement already satisfied: importlib-metadata!=4.7.0,<6,>=3.7.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (4.13.0)
Requirement already satisfied: Flask<3 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (2.2.2)
Requirement already satisfied: protobuf<5,>=3.12.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (3.20.3)
Requirement already satisfied: entrypoints<1 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (0.4)
Requirement already satisfied: alembic<2 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (1.9.1)
Collecting prometheus-flask-exporter<1
  Downloading prometheus_flask_exporter-0.21.0-py3-none-any.whl (18 kB)
Requirement already satisfied: gitpython<4,>=2.1.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (3.1.27)
Requirement already satisfied: docker<7,>=4.0.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (5.0.3)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (8.1.3)
Collecting gunicorn<21
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.3 MB/s eta 0:00:00
Collecting querystring-parser<2
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Requirement already satisfied: sqlalchemy<2,>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (1.4.39)
Collecting databricks-cli<1,>=0.8.7
  Downloading databricks-cli-0.17.4.tar.gz (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.3/82.3 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cloudpickle<3 in /opt/conda/lib/python3.7/site-packages (from mlflow->pycaret) (2.1.0)
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.7/site-packages (from nltk->pycaret) (2021.11.10)
Requirement already satisfied: numexpr in /opt/conda/lib/python3.7/site-packages (from pyLDAvis->pycaret) (2.8.4)
Requirement already satisfied: future in /opt/conda/lib/python3.7/site-packages (from pyLDAvis->pycaret) (0.18.2)
Requirement already satisfied: funcy in /opt/conda/lib/python3.7/site-packages (from pyLDAvis->pycaret) (1.17)
Requirement already satisfied: statsmodels in /opt/conda/lib/python3.7/site-packages (from pyod->pycaret) (0.13.2)
Requirement already satisfied: pynndescent>=0.5 in /opt/conda/lib/python3.7/site-packages (from umap-learn->pycaret) (0.5.8)
Requirement already satisfied: Mako in /opt/conda/lib/python3.7/site-packages (from alembic<2->mlflow->pycaret) (1.2.4)
Requirement already satisfied: importlib-resources in /opt/conda/lib/python3.7/site-packages (from alembic<2->mlflow->pycaret) (5.10.2)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from catalogue<1.1.0,>=0.0.7->spacy<2.4.0->pycaret) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from catalogue<1.1.0,>=0.0.7->spacy<2.4.0->pycaret) (4.1.1)
Requirement already satisfied: pyjwt>=1.7.0 in /opt/conda/lib/python3.7/site-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret) (2.4.0)
Requirement already satisfied: oauthlib>=3.1.0 in /opt/conda/lib/python3.7/site-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret) (3.2.0)
Requirement already satisfied: tabulate>=0.7.7 in /opt/conda/lib/python3.7/site-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret) (0.9.0)
Requirement already satisfied: websocket-client>=0.32.0 in /opt/conda/lib/python3.7/site-packages (from docker<7,>=4.0.0->mlflow->pycaret) (1.3.3)
Requirement already satisfied: itsdangerous>=2.0 in /opt/conda/lib/python3.7/site-packages (from Flask<3->mlflow->pycaret) (2.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in /opt/conda/lib/python3.7/site-packages (from Flask<3->mlflow->pycaret) (2.2.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.7/site-packages (from gitpython<4,>=2.1.0->mlflow->pycaret) (4.0.9)
Requirement already satisfied: tornado>=6.1 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1)
Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (23.2.0)
Requirement already satisfied: debugpy>=1.0 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.6.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (7.3.4)
Requirement already satisfied: psutil in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.9.1)
Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.5.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.7/site-packages (from jedi>=0.16->IPython->pycaret) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.7/site-packages (from pexpect>4.3->IPython->pycaret) (0.7.0)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.7/site-packages (from prometheus-flask-exporter<1->mlflow->pycaret) (0.14.1)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pycaret) (0.2.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.26.13)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2022.12.7)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.7/site-packages (from sqlalchemy<2,>=1.4.0->mlflow->pycaret) (1.1.2)
Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.7/site-packages (from widgetsnbextension~=3.6.0->ipywidgets->pycaret) (6.4.12)
Requirement already satisfied: patsy>=0.5.2 in /opt/conda/lib/python3.7/site-packages (from statsmodels->pyod->pycaret) (0.5.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.7/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow->pycaret) (3.0.5)
Requirement already satisfied: jupyter-core>=4.9.2 in /opt/conda/lib/python3.7/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->pycaret) (4.10.0)
Requirement already satisfied: nbconvert>=5 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (6.4.5)
Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (21.3.0)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.15.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (1.8.0)

In [52]:
from pycaret.anomaly import *

ModuleNotFoundError: No module named 'pycaret'

In [ ]:
_ = pycaret.anomaly.setup(
    data=space_df[tr_idx],
    silent=True)

In [ ]:
knn = pycaret.anomaly.create_model('knn')

In [53]:
knn_df = pycaret.anomaly.assign_model(knn)
abnormal_data = knn_df[knn_df.Anomaly == 1].sort_values(by='Anomaly_Score', ascending=False)
print("the size of anomaly = ",len(abnormal_data))
abnormal_data.head().style.set_properties(**{'background-color': 'black',
                           'color': 'white',
                           'border-color': 'white'})

NameError: name 'pycaret' is not defined

In [49]:
plt.style.use("dark_background")
plot_model(knn,plot='umap')

NameError: name 'plot_model' is not defined

---

## || Cartesian coordinates rotation

---

In [8]:
def crt_crds(df):
    
    df['rot_15_x'] = (np.cos(np.radians(15)) * df['Longitude']) + \
                      (np.sin(np.radians(15)) * df['Latitude'])
    
    df['rot_15_y'] = (np.cos(np.radians(15)) * df['Latitude']) + \
                      (np.sin(np.radians(15)) * df['Longitude'])
    
    df['rot_30_x'] = (np.cos(np.radians(30)) * df['Longitude']) + \
                      (np.sin(np.radians(30)) * df['Latitude'])
    
    df['rot_30_y'] = (np.cos(np.radians(30)) * df['Latitude']) + \
                      (np.sin(np.radians(30)) * df['Longitude'])
    
    df['rot_45_x'] = (np.cos(np.radians(45)) * df['Longitude']) + \
                      (np.sin(np.radians(45)) * df['Latitude'])
    return df

# train_df = crt_crds(train_df)
# test_df = crt_crds(test_df)
df = crt_crds(df)

In [18]:
df['rot_45_x'] = (np.cos(np.radians(45)) * df['Longitude']) + \
                  (np.sin(np.radians(45)) * df['Latitude'])
    
df['rot_45_y'] = (np.cos(np.radians(45)) * df['Latitude']) + \
                  (np.sin(np.radians(45)) * df['Longitude'])
    
df['rot_135_x'] = (np.cos(np.radians(135)) * df['Longitude']) + \
                  (np.sin(np.radians(135)) * df['Latitude'])
    
df['rot_135_y'] = (np.cos(np.radians(135)) * df['Latitude']) + \
                  (np.sin(np.radians(135)) * df['Longitude'])
    
df['rot_270_x'] = (np.cos(np.radians(270)) * df['Longitude']) + \
                  (np.sin(np.radians(270)) * df['Latitude'])

df['rot_270_y'] = (np.cos(np.radians(270)) * df['Longitude']) + \
                  (np.sin(np.radians(270)) * df['Latitude'])

## || Location of coordinates

In [9]:
pip install reverse_geocoder

Collecting reverse_geocoder
  Downloading reverse_geocoder-1.5.1.tar.gz (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 4.6 MB/s eta 0:00:0000:0100:010m
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.11.0 in /opt/conda/lib/python3.7/site-packages (from reverse_geocoder) (1.21.6)
Requirement already satisfied: scipy>=0.17.1 in /opt/conda/lib/python3.7/site-packages (from reverse_geocoder) (1.7.3)
Building wheels for collected packages: reverse_geocoder
  Building wheel for reverse_geocoder (setup.py) ... done
  Created wheel for reverse_geocoder: filename=reverse_geocoder-1.5.1-py3-none-any.whl size=2268088 sha256=095f2f99ed139fc20b0597946f4d38c300e493ac9959675705b38aba3da53464
  Stored in directory: /root/.cache/pip/wheels/34/6e/70/5423639428a2cac8ea7eb467214a4254b549b381f306a9c790
Successfully built reverse_geocoder
Installing collected packages: reverse_geocoder
Successfully installed reverse_geocoder-1.5.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [10]:
import reverse_geocoder as rg

coordinates = list(zip(df['Latitude'], df['Longitude']))
results = rg.search(coordinates)
df['place'] = [x['admin2'] for x in results]

places = ['Los Angeles County', 'Orange County', 'Kern County',
          'Alameda County', 'San Francisco County', 'Ventura County',
          'Santa Clara County', 'Fresno County', 'Santa Barbara County',
          'Contra Costa County', 'Yolo County', 'Monterey County',
          'Riverside County', 'Napa County']

def replace(x):
    if x in places:
        return x
    else:
        return 'Other'
    
df['place'] = df['place'].apply(lambda x: replace(x))
le = LabelEncoder()
df['place'] = le.fit_transform(df['place'])

Loading formatted geocoded file...

## || Distance to cities, coast points & parcs

In [12]:
from haversine import haversine

Sac = (38.576931, -121.494949)
SF = (37.780080, -122.420160)
SJ = (37.334789, -121.888138)
LA = (34.052235, -118.243683)
SD = (32.715759, -117.163818)

Yosemite = (37.866747, -119.538076)
Sequoia = (36.489057, -118.565255)
Kings_Canyon = (36.887855, -118.555146)
Death_Valley = (36.464288, -116.869045)
Joshua_Tree = (34.133831, -116.314867)

# Biggers Towns :
df['dist_Sac'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), Sac, unit='ft'), axis=1)
df['dist_SF'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), SF, unit='ft'), axis=1)
df['dist_SJ'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), SJ, unit='ft'), axis=1)
df['dist_LA'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), LA, unit='ft'), axis=1)
df['dist_SD'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), SD, unit='ft'), axis=1)

# Biggers Parks :
df['dist_Yosemite'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), Yosemite, unit='ft'), axis=1)
df['dist_Sequoia'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), Sequoia, unit='ft'), axis=1)
df['dist_Kings_Canyon'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), Kings_Canyon, unit='ft'), axis=1)
df['dist_Death_Valley'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), Death_Valley, unit='ft'), axis=1)
df['dist_Joshua_Tree'] = df.apply(lambda x: haversine((x['Latitude'], x['Longitude']), Joshua_Tree, unit='ft'), axis=1)

df['dist_nearest_city'] = df[['dist_Sac', 'dist_SF', 'dist_SJ', 'dist_LA', 'dist_SD']].min(axis=1)
df['dist_nearest_parc'] = df[['dist_Yosemite', 'dist_Sequoia', 'dist_Kings_Canyon','dist_Death_Valley', 'dist_Joshua_Tree']].min(axis=1)

In [18]:
import folium
from folium import plugins
from folium.plugins import HeatMap

In [19]:
heat_map = folium.Map(train[['Latitude', 'Longitude']].mean(axis=0),
                    zoom_start = 6) 

train['Latitude'] = train['Latitude'].astype(float)
train['Longitude'] = train['Longitude'].astype(float)

lat_long_list = [[row['Latitude'],row['Longitude']] for index, row in train.iterrows()]
HeatMap(lat_long_list, radius=10).add_to(heat_map)
heat_map

In [20]:
from shapely.geometry import LineString, Point

coast_points = LineString([(32.6644, -117.1613), (33.2064, -117.3831),
                           (33.7772, -118.2024), (34.4634, -120.0144),
                           (35.4273, -120.8819), (35.9284, -121.4892),
                           (36.9827, -122.0289), (37.6114, -122.4916),
                           (38.3556, -123.0603), (39.7926, -123.8217),
                           (40.7997, -124.1881), (41.7558, -124.1976)])

df['dist_to_coast'] = df.apply(lambda x: Point(x['Latitude'], x['Longitude']).distance(coast_points), axis=1)

df['dist_to_'] = df.apply(lambda x: Point(x['Latitude'], x['Longitude']).distance(coast_points), axis=1)



# 📌 Improvement possible with 2 differents variable creation : string Lines X 
# 📌                                                            string Lines +

## || Final preprocessing

In [21]:
train = df.iloc[:-len(test),:]
test = df.iloc[-len(test):,:].drop('MedHouseVal', axis=1).reset_index(drop=True)

X = train.drop('MedHouseVal', axis=1)
y = train['MedHouseVal']

seed = 228
FOLDS = 10

In [22]:
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

def f_importance_plot(f_imp):
    fig = plt.figure(figsize = (15, 0.35*len(f_imp)))
    plt.title('Feature importances', size=25, y=1.05, 
              fontname='Calibri', fontweight='bold', color='#444444')
    a = sns.barplot(data=f_imp, x='avg_imp', y='feature', 
                    palette='Blues_d', linestyle="-", 
                    linewidth=1, edgecolor="black")
    plt.xlabel('')
    plt.xticks([])
    plt.ylabel('')
    plt.yticks(size=11, color='#444444')
    
    for j in ['right', 'top', 'bottom']:
        a.spines[j].set_visible(False)
    for j in ['left']:
        a.spines[j].set_linewidth(0.5)
    plt.show()

In [23]:
train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal,is_generated,exp_latlon1,exp_latlon2,pca_lat,pca_lon,umap_lat,umap_lon,rot_15_x,rot_15_y,rot_30_x,rot_30_y,rot_45_x,place,dist_Sac,dist_SF,dist_SJ,dist_LA,dist_SD,dist_Yosemite,dist_Sequoia,dist_Kings_Canyon,dist_Death_Valley,dist_Joshua_Tree,dist_nearest_city,dist_nearest_parc,dist_to_coast,dist_to_
0,2.3859,15.0,3.827160,1.112100,1280.0,2.486989,34.60,-120.12,0.980,1,-0.999098,-0.078880,-0.342723,-1.086666,4.196439,11.288356,-107.071871,2.331690,-86.726972,-30.095521,-60.471772,11,1.505644e+06,1.343215e+06,1.125962e+06,5.995613e+05,1.130527e+06,1.203984e+06,8.293757e+05,9.545868e+05,1.180583e+06,1.158322e+06,599561.346601,829375.663564,0.012888,0.012888
1,3.7188,17.0,6.013373,1.054217,1504.0,3.813084,38.69,-121.22,0.946,1,0.547947,0.974193,3.391118,0.912466,17.744240,-1.431677,-107.075820,5.997626,-85.634599,-27.103477,-58.357523,8,8.854832e+04,4.779710e+05,5.303822e+05,1.904151e+06,2.488078e+06,5.676190e+05,1.110590e+06,1.011098e+06,1.496985e+06,2.198480e+06,88548.323144,567618.987857,1.665273,1.665273
2,4.7750,27.0,6.535604,1.103175,1061.0,2.464602,34.71,-120.45,1.576,1,-0.988397,0.140055,-0.036583,-1.251827,8.670680,-1.934410,-107.362157,2.352531,-86.957760,-30.165258,-60.627335,11,1.443453e+06,1.261031e+06,1.047325e+06,7.062707e+05,1.234280e+06,1.182411e+06,8.565765e+05,9.723635e+05,1.240124e+06,1.261930e+06,706270.711605,856576.480476,0.158815,0.158815
3,2.4138,16.0,3.350203,0.965432,1255.0,2.089286,32.66,-117.09,1.336,1,0.320941,0.723030,-3.831383,-0.207032,-2.469708,-14.047390,-104.647225,1.242015,-85.072915,-30.260610,-59.701026,8,2.522266e+06,2.451054e+06,2.227410e+06,6.176880e+05,3.045445e+04,2.034423e+06,1.465434e+06,1.603581e+06,1.389440e+06,5.872150e+05,30454.454611,587214.987893,0.071436,0.071436
4,3.7500,52.0,4.284404,1.069246,1793.0,1.604790,37.80,-122.41,4.500,1,0.994915,0.022690,3.557422,-0.564200,33.871826,13.683404,-108.455620,4.829957,-87.110170,-28.469240,-59.828305,10,3.862307e+05,7.835185e+03,2.271009e+05,1.839177e+06,2.424468e+06,8.278093e+05,1.215906e+06,1.166387e+06,1.683307e+06,2.241369e+06,7835.184568,827809.308562,0.179351,0.179351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57772,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781,0,-0.208550,-0.231034,3.877808,1.548180,8.378905,7.506400,-106.745782,6.794353,-85.127016,-26.354317,-57.706984,8,3.488665e+05,7.268149e+05,8.151728e+05,2.147412e+06,2.724824e+06,7.360091e+05,1.310428e+06,1.192609e+06,1.637891e+06,2.396890e+06,348866.508021,736009.143611,2.248242,2.248242
57773,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771,0,-0.218319,-0.250399,3.967270,1.467578,8.889896,7.032233,-106.859105,6.772954,-85.225939,-26.405657,-57.784766,8,3.427467e+05,7.127612e+05,8.097853e+05,2.164527e+06,2.743236e+06,7.598418e+05,1.332803e+06,1.216686e+06,1.665952e+06,2.420292e+06,342746.711259,759841.797908,2.158966,2.158966
57774,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923,0,-0.159409,-0.132982,3.930392,1.419204,8.859087,7.053589,-106.884294,6.712411,-85.264599,-26.462618,-57.834264,8,3.208235e+05,6.923452e+05,7.878722e+05,2.145811e+06,2.725036e+06,7.448688e+05,1.316733e+06,1.201712e+06,1.654102e+06,2.404744e+06,320823.532421,744868.778161,2.114589,2.114589
57775,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847,0,-0.159409,-0.132982,3.998871,1.346329,8.975849,6.858022,-106.980886,6.686529,-85.351202,-26.512618,-57.904974,8,3.151381e+05,6.787121e+05,7.814318e+05,2.157805e+06,2.738064e+06,7.635060e+05,1.333606e+06,1.220148e+06,1.675955e+06,2.422230e+06,315138.110115,763505.997825,2.035133,2.035133
57776,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894,0,-0.099925,-0.013661,3.900363,1.363542,8.802337,7.130656,-106.919141,6.649279,-85.311920,-26.524580,-57.890832,8,2.982206e+05,6.705958e+05,7.652691e+05,2.128360e+06,2.708200e+06,7.321442e+05,1.302538e+06,1.188819e+06,1.644665e+06,2.391055e+06,298220.615351,732144.189728,2.062267,2.062267

---

# Best feature selection with ROC_AUC adapted :

---

# /ToDo : Implémenter MMR pour la feature selection.

# ...

---

# Model 1 : CatBoost

---

In [26]:
import catboost
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

n_folds = 10

MAX_ITER = 22500
PATIENCE = 1500
DISPLAY_FREQ = 100

eval_predsCB = []
predsCB = []

k_fold = KFold(n_splits=n_folds, random_state=51, shuffle = True)

MODEL_PARAMS = {
                'random_seed': 51,    
                'iterations': MAX_ITER,
                'early_stopping_rounds': PATIENCE,
                'use_best_model': True,
                'eval_metric': 'RMSE',
                'verbose': 4500,
               }

In [27]:
X = train.drop(columns=['MedHouseVal'])
y = train.MedHouseVal
X_test = test

In [28]:
for train_index, test_index in k_fold.split(X, y):
    X_train, X_valid = X.iloc[train_index], X.iloc[test_index]
    y_train, y_valid = y.iloc[train_index], y.iloc[test_index]
    
    model = catboost.CatBoostRegressor(**MODEL_PARAMS)
    
    model.fit(X=X_train, y=y_train,
          eval_set=[(X_valid, y_valid)],
          early_stopping_rounds = PATIENCE,
         )
    predsCB.append(model.predict(X_test))
#     eval_predsCB.append(model.predict(X))
#     print("RMSE valid = {}".format(mean_squared_error(y_valid, model.predict(X_valid))))
#     print("RMSE full = {}".format(mean_squared_error(y, model.predict(X))))

Learning rate set to 0.014173
0:	learn: 1.1482419	test: 1.1314880	best: 1.1314880 (0)	total: 81.2ms	remaining: 30m 26s
4500:	learn: 0.4610418	test: 0.5019047	best: 0.5019047 (4500)	total: 58.7s	remaining: 3m 54s
9000:	learn: 0.4217495	test: 0.4972462	best: 0.4972332 (8865)	total: 1m 57s	remaining: 2m 56s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.4968257761
bestIteration = 10245

Shrink model to first 10246 iterations.
Learning rate set to 0.014173
0:	learn: 1.1454066	test: 1.1572453	best: 1.1572453 (0)	total: 14.7ms	remaining: 5m 30s
4500:	learn: 0.4592622	test: 0.5247496	best: 0.5247469 (4499)	total: 59s	remaining: 3m 55s
9000:	learn: 0.4206214	test: 0.5214844	best: 0.5214841 (8999)	total: 1m 57s	remaining: 2m 56s
13500:	learn: 0.3920471	test: 0.5207711	best: 0.5207675 (13492)	total: 2m 58s	remaining: 1m 58s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5207103183
bestIteration = 14742

Shrink model to first 14743 iterations.
Learning rate set to 0.014173
0:	learn: 1.1454406	test: 1.1570517	best: 1.1570517 (0)	total: 16.1ms	remaining: 6m 3s
4500:	learn: 0.4597530	test: 0.5066642	best: 0.5066642 (4500)	total: 58.1s	remaining: 3m 52s
9000:	learn: 0.4212843	test: 0.5026798	best: 0.5026711 (8996)	total: 1m 56s	remaining: 2m 54s
13500:	learn: 0.3930695	test: 0.5016991	best: 0.5016753 (13362)	total: 2m 55s	remaining: 1m 56s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.501580294
bestIteration = 15017

Shrink model to first 15018 iterations.
Learning rate set to 0.014173
0:	learn: 1.1460597	test: 1.1511498	best: 1.1511498 (0)	total: 14.2ms	remaining: 5m 19s
4500:	learn: 0.4607611	test: 0.5034352	best: 0.5034151 (4489)	total: 58.2s	remaining: 3m 52s
9000:	learn: 0.4215336	test: 0.5004321	best: 0.5003758 (8919)	total: 1m 56s	remaining: 2m 54s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5003205971
bestIteration = 9374

Shrink model to first 9375 iterations.
Learning rate set to 0.014173
0:	learn: 1.1472120	test: 1.1410278	best: 1.1410278 (0)	total: 16.2ms	remaining: 6m 3s
4500:	learn: 0.4592162	test: 0.5046796	best: 0.5046732 (4495)	total: 58.8s	remaining: 3m 55s
9000:	learn: 0.4206634	test: 0.5014934	best: 0.5014657 (8966)	total: 1m 57s	remaining: 2m 55s
13500:	learn: 0.3918793	test: 0.5008641	best: 0.5006750 (12377)	total: 2m 56s	remaining: 1m 57s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5006749774
bestIteration = 12377

Shrink model to first 12378 iterations.
Learning rate set to 0.014173
0:	learn: 1.1469401	test: 1.1429598	best: 1.1429598 (0)	total: 16.2ms	remaining: 6m 3s
4500:	learn: 0.4586527	test: 0.5231521	best: 0.5231456 (4497)	total: 59.5s	remaining: 3m 57s
9000:	learn: 0.4197598	test: 0.5209517	best: 0.5209093 (8858)	total: 1m 58s	remaining: 2m 57s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5205087555
bestIteration = 10803

Shrink model to first 10804 iterations.
Learning rate set to 0.014173
0:	learn: 1.1464139	test: 1.1478925	best: 1.1478925 (0)	total: 17.6ms	remaining: 6m 34s
4500:	learn: 0.4593974	test: 0.5164389	best: 0.5164360 (4499)	total: 1m	remaining: 4m 1s
9000:	learn: 0.4202756	test: 0.5118203	best: 0.5117864 (8978)	total: 2m 10s	remaining: 3m 15s
13500:	learn: 0.3918278	test: 0.5108952	best: 0.5108819 (13486)	total: 3m 11s	remaining: 2m 7s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5107798809
bestIteration = 14162

Shrink model to first 14163 iterations.
Learning rate set to 0.014173
0:	learn: 1.1472523	test: 1.1403481	best: 1.1403481 (0)	total: 14.9ms	remaining: 5m 34s
4500:	learn: 0.4601034	test: 0.5072789	best: 0.5072789 (4500)	total: 59.9s	remaining: 3m 59s
9000:	learn: 0.4209006	test: 0.5025004	best: 0.5024869 (8948)	total: 2m	remaining: 3m
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5018017403
bestIteration = 11719

Shrink model to first 11720 iterations.
Learning rate set to 0.014173
0:	learn: 1.1445102	test: 1.1649380	best: 1.1649380 (0)	total: 14.4ms	remaining: 5m 23s
4500:	learn: 0.4591814	test: 0.5148161	best: 0.5148154 (4499)	total: 1m 1s	remaining: 4m 4s
9000:	learn: 0.4202354	test: 0.5118390	best: 0.5118390 (9000)	total: 2m 1s	remaining: 3m 2s
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.5118327782
bestIteration = 9002

Shrink model to first 9003 iterations.
Learning rate set to 0.014173
0:	learn: 1.1482542	test: 1.1313964	best: 1.1313964 (0)	total: 14.5ms	remaining: 5m 27s
4500:	learn: 0.4608931	test: 0.5014548	best: 0.5014536 (4495)	total: 1m	remaining: 4m 1s
9000:	learn: 0.4227913	test: 0.4977089	best: 0.4976849 (8953)	total: 2m	remaining: 3m
Stopped by overfitting detector  (1500 iterations wait)

bestTest = 0.4973815548
bestIteration = 11748

Shrink model to first 11749 iterations.

---

# Model 2 : XGBoost

---

In [39]:
# Extraction de la data pour traitement du tuning XGB au GPU dans un autre Notebook : 
train.to_csv("train_full.csv")

In [38]:
from xgboost import XGBRegressor

n_folds = 9
k_fold = KFold(n_splits=n_folds, random_state=51, shuffle=True)

eval_predsXB = []
predsXB = []

PATIENCE = 200

MODEL_PARAMS = {       'n_estimators': 15000, #1000, 5000
                       #'learning_rate': 0.02,
                       'max_depth': 4,
                       'colsample_bytree': 0.66, # 0.95
                       'subsample': 1,
                       'reg_lambda': 20,
                       'early_stopping_rounds': PATIENCE,
#                      'tree_method': 'gpu_hist',
                       'seed': 1
}

for train_index, test_index in k_fold.split(X, y):
    X_train, X_valid = X.iloc[train_index], X.iloc[test_index]
    y_train, y_valid = y.iloc[train_index], y.iloc[test_index]
    
    model = XGBRegressor(**MODEL_PARAMS)
    
    model.fit(X=X_train, y=y_train,
          eval_set=[(X_valid, y_valid)],
#           early_stopping_rounds = PATIENCE,
          verbose = 200
         )
    predsXB.append(model.predict(X_test))
#     eval_predsXB.append(model.predict(X))

[0]	validation_0-rmse:1.48390
[200]	validation_0-rmse:0.51571
[400]	validation_0-rmse:0.51230
[600]	validation_0-rmse:0.51127
[744]	validation_0-rmse:0.51168
[0]	validation_0-rmse:1.51237
[200]	validation_0-rmse:0.53083
[400]	validation_0-rmse:0.52763
[600]	validation_0-rmse:0.52762
[718]	validation_0-rmse:0.52805
[0]	validation_0-rmse:1.53246
[200]	validation_0-rmse:0.52286
[400]	validation_0-rmse:0.51966
[600]	validation_0-rmse:0.52018
[630]	validation_0-rmse:0.52016
[0]	validation_0-rmse:1.48912
[200]	validation_0-rmse:0.51214
[400]	validation_0-rmse:0.51170
[600]	validation_0-rmse:0.51156
[650]	validation_0-rmse:0.51153
[0]	validation_0-rmse:1.52539
[200]	validation_0-rmse:0.52285
[400]	validation_0-rmse:0.52136
[511]	validation_0-rmse:0.52138
[0]	validation_0-rmse:1.51068
[200]	validation_0-rmse:0.53498
[400]	validation_0-rmse:0.53280
[600]	validation_0-rmse:0.53176
[800]	validation_0-rmse:0.53123
[1000]	validation_0-rmse:0.53275
[1025]	validation_0-rmse:0.53266
[0]	validation_0-rmse:1.49955
[200]	validation_0-rmse:0.50857
[400]	validation_0-rmse:0.50468
[600]	validation_0-rmse:0.50368
[800]	validation_0-rmse:0.50400
[876]	validation_0-rmse:0.50465
[0]	validation_0-rmse:1.51664
[200]	validation_0-rmse:0.52753
[400]	validation_0-rmse:0.52715
[470]	validation_0-rmse:0.52714
[0]	validation_0-rmse:1.48740
[200]	validation_0-rmse:0.51786
[400]	validation_0-rmse:0.51619
[535]	validation_0-rmse:0.51688

In [61]:
pip install autogluon

Collecting autogluon
  Downloading autogluon-0.6.1-py3-none-any.whl (9.8 kB)
Collecting autogluon.multimodal==0.6.1
  Downloading autogluon.multimodal-0.6.1-py3-none-any.whl (289 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.7/289.7 kB 527.9 kB/s eta 0:00:0000:0100:01
Collecting autogluon.core[all]==0.6.1
  Downloading autogluon.core-0.6.1-py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.6/226.6 kB 3.3 MB/s eta 0:00:00a 0:00:01
Collecting autogluon.tabular[all]==0.6.1
  Downloading autogluon.tabular-0.6.1-py3-none-any.whl (286 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.0/286.0 kB 4.5 MB/s eta 0:00:00a 0:00:01
Collecting autogluon.vision==0.6.1
  Downloading autogluon.vision-0.6.1-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 kB 3.2 MB/s eta 0:00:00
Collecting autogluon.features==0.6.1
  Downloading autogluon.features-0.6.1-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 3.7 MB/s eta 0:00:00
Collecting autogluon.timeseries[all]==0.6.1
  Downloading autogluon.timeseries-0.6.1-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.0/103.0 kB 4.7 MB/s eta 0:00:00
Collecting autogluon.text==0.6.1
  Downloading autogluon.text-0.6.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 4.3 MB/s eta 0:00:00
Collecting dask<=2021.11.2,>=2021.09.1
  Downloading dask-2021.11.2-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 4.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: scipy<1.10.0,>=1.5.4 in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (1.7.3)
Collecting autogluon.common==0.6.1
  Downloading autogluon.common-0.6.1-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 kB 3.4 MB/s eta 0:00:00
Collecting numpy<1.24,>=1.21
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 15.3 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scikit-learn<1.2,>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (1.0.2)
Requirement already satisfied: tqdm>=4.38.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (4.64.0)
Requirement already satisfied: boto3 in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (1.26.43)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (2.28.1)
Requirement already satisfied: pandas!=1.4.0,<1.6,>=1.2.5 in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (1.3.5)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (3.5.3)
Collecting distributed<=2021.11.2,>=2021.09.1
  Downloading distributed-2021.11.2-py3-none-any.whl (802 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.2/802.2 kB 44.5 MB/s eta 0:00:00
Collecting ray[tune]<2.1,>=2.0
  Downloading ray-2.0.1-cp37-cp37m-manylinux2014_x86_64.whl (60.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.5/60.5 MB 10.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /opt/conda/lib/python3.7/site-packages (from autogluon.core[all]==0.6.1->autogluon) (0.2.7)
Requirement already satisfied: psutil<6,>=5.7.3 in /opt/conda/lib/python3.7/site-packages (from autogluon.features==0.6.1->autogluon) (5.9.1)
Collecting transformers<4.24.0,>=4.23.0
  Downloading transformers-4.23.1-py3-none-any.whl (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 22.1 MB/s eta 0:00:0000:0100:01
Collecting torchmetrics<0.9.0,>=0.8.0
  Downloading torchmetrics-0.8.2-py3-none-any.whl (409 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.8/409.8 kB 30.5 MB/s eta 0:00:00
Requirement already satisfied: accelerate<0.14,>=0.9 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.12.0)
Collecting pytorch-metric-learning<1.4.0,>=1.3.0
  Downloading pytorch_metric_learning-1.3.2-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.4/109.4 kB 9.4 MB/s eta 0:00:00
Collecting timm<0.7.0
  Downloading timm-0.6.12-py3-none-any.whl (549 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.1/549.1 kB 34.2 MB/s eta 0:00:00
Collecting evaluate<=0.3.0
  Downloading evaluate-0.3.0-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: fairscale<=0.4.6,>=0.4.5 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.4.6)
Collecting seqeval<=1.2.2
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting smart-open<5.3.0,>=5.2.1
  Downloading smart_open-5.2.1-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: text-unidecode<=1.3 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (1.3)
Requirement already satisfied: sentencepiece<0.2.0,>=0.1.95 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.1.97)
Requirement already satisfied: scikit-image<0.20.0,>=0.19.1 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.19.3)
Collecting nlpaug<=1.1.10,>=1.1.10
  Downloading nlpaug-1.1.10-py3-none-any.whl (410 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.8/410.8 kB 28.6 MB/s eta 0:00:00
Requirement already satisfied: nltk<4.0.0,>=3.4.5 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (3.8.1)
Collecting omegaconf<2.2.0,>=2.1.1
  Downloading omegaconf-2.1.2-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.7/74.7 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: defusedxml<=0.7.1,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.7.1)
Collecting nptyping<1.5.0,>=1.4.4
  Downloading nptyping-1.4.4-py3-none-any.whl (31 kB)
Requirement already satisfied: torch<1.13,>=1.9 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (1.11.0+cpu)
Requirement already satisfied: torchtext<0.14.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.12.0)
Collecting pytorch-lightning<1.8.0,>=1.7.4
  Downloading pytorch_lightning-1.7.7-py3-none-any.whl (708 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 708.1/708.1 kB 43.5 MB/s eta 0:00:00
Requirement already satisfied: jsonschema<=4.8.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (4.6.1)
Collecting Pillow<=9.4.0,>=9.3.0
  Using cached Pillow-9.4.0-cp37-cp37m-manylinux_2_28_x86_64.whl (3.4 MB)
Requirement already satisfied: torchvision<0.14.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.multimodal==0.6.1->autogluon) (0.12.0+cpu)
Collecting albumentations<=1.2.0,>=1.1.0
  Downloading albumentations-1.2.0-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.5/113.5 kB 10.9 MB/s eta 0:00:00
Collecting openmim<=0.2.1,>0.1.5
  Downloading openmim-0.2.1-py2.py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: networkx<3.0,>=2.3 in /opt/conda/lib/python3.7/site-packages (from autogluon.tabular[all]==0.6.1->autogluon) (2.5)
Requirement already satisfied: lightgbm<3.4,>=3.3 in /opt/conda/lib/python3.7/site-packages (from autogluon.tabular[all]==0.6.1->autogluon) (3.3.2)
Requirement already satisfied: fastai<2.8,>=2.3.1 in /opt/conda/lib/python3.7/site-packages (from autogluon.tabular[all]==0.6.1->autogluon) (2.7.10)
Requirement already satisfied: catboost<1.2,>=1.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.tabular[all]==0.6.1->autogluon) (1.1.1)
Requirement already satisfied: xgboost<1.8,>=1.6 in /opt/conda/lib/python3.7/site-packages (from autogluon.tabular[all]==0.6.1->autogluon) (1.6.2)
Collecting joblib~=1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 26.4 MB/s eta 0:00:00
Requirement already satisfied: statsmodels~=0.13.0 in /opt/conda/lib/python3.7/site-packages (from autogluon.timeseries[all]==0.6.1->autogluon) (0.13.2)
Collecting gluonts~=0.11.0
  Downloading gluonts-0.11.7-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 44.5 MB/s eta 0:00:00
Collecting psutil<6,>=5.7.3
  Downloading psutil-5.8.0-cp37-cp37m-manylinux2010_x86_64.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.3/296.3 kB 21.2 MB/s eta 0:00:00
Collecting sktime<0.14,>=0.13.1
  Downloading sktime-0.13.4-py3-none-any.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 17.4 MB/s eta 0:00:0000:0100:01
Collecting tbats~=1.1
  Downloading tbats-1.1.2-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 3.8 MB/s eta 0:00:00
Collecting pmdarima~=1.8.2
  Downloading pmdarima-1.8.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 47.4 MB/s eta 0:00:00
Requirement already satisfied: gluoncv<0.10.6,>=0.10.5 in /opt/conda/lib/python3.7/site-packages (from autogluon.vision==0.6.1->autogluon) (0.10.5.post0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from autogluon.common==0.6.1->autogluon.core[all]==0.6.1->autogluon) (59.8.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from accelerate<0.14,>=0.9->autogluon.multimodal==0.6.1->autogluon) (21.3)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from accelerate<0.14,>=0.9->autogluon.multimodal==0.6.1->autogluon) (5.4.1)
Collecting albumentations<=1.2.0,>=1.1.0
  Downloading albumentations-1.1.0-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.4/102.4 kB 10.1 MB/s eta 0:00:00
Requirement already satisfied: qudida>=0.0.4 in /opt/conda/lib/python3.7/site-packages (from albumentations<=1.2.0,>=1.1.0->autogluon.multimodal==0.6.1->autogluon) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /opt/conda/lib/python3.7/site-packages (from albumentations<=1.2.0,>=1.1.0->autogluon.multimodal==0.6.1->autogluon) (4.5.4.60)
Requirement already satisfied: plotly in /opt/conda/lib/python3.7/site-packages (from catboost<1.2,>=1.0->autogluon.tabular[all]==0.6.1->autogluon) (5.11.0)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.7/site-packages (from catboost<1.2,>=1.0->autogluon.tabular[all]==0.6.1->autogluon) (0.8.4)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from catboost<1.2,>=1.0->autogluon.tabular[all]==0.6.1->autogluon) (1.15.0)
Requirement already satisfied: toolz>=0.8.2 in /opt/conda/lib/python3.7/site-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (0.11.2)
Requirement already satisfied: fsspec>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (2022.11.0)
Requirement already satisfied: partd>=0.3.10 in /opt/conda/lib/python3.7/site-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (1.3.0)
Requirement already satisfied: cloudpickle>=1.1.1 in /opt/conda/lib/python3.7/site-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (2.1.0)
Requirement already satisfied: tblib>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (1.7.0)
Requirement already satisfied: tornado>=5 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (6.1)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (2.4.0)
Requirement already satisfied: msgpack>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (1.0.4)
Requirement already satisfied: zict>=0.1.3 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (2.2.0)
Requirement already satisfied: click>=6.6 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (8.1.3)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.6.1->autogluon) (3.1.2)
Requirement already satisfied: responses<0.19 in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (0.18.0)
Requirement already satisfied: datasets>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (2.1.0)
Requirement already satisfied: dill in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (0.3.6)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (0.70.14)
Requirement already satisfied: huggingface-hub>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (0.10.1)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (4.13.0)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.7/site-packages (from evaluate<=0.3.0->autogluon.multimodal==0.6.1->autogluon) (3.2.0)
Requirement already satisfied: pip in /opt/conda/lib/python3.7/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.6.1->autogluon) (22.1.2)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /opt/conda/lib/python3.7/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.6.1->autogluon) (0.0.7)
Requirement already satisfied: spacy<4 in /opt/conda/lib/python3.7/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.6.1->autogluon) (3.3.2)
Requirement already satisfied: fastcore<1.6,>=1.4.5 in /opt/conda/lib/python3.7/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.6.1->autogluon) (1.5.27)
Requirement already satisfied: fastprogress>=0.2.4 in /opt/conda/lib/python3.7/site-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==0.6.1->autogluon) (1.0.3)
Requirement already satisfied: autocfg in /opt/conda/lib/python3.7/site-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.6.1->autogluon) (0.0.8)
Requirement already satisfied: yacs in /opt/conda/lib/python3.7/site-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.6.1->autogluon) (0.1.8)
Requirement already satisfied: opencv-python in /opt/conda/lib/python3.7/site-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.6.1->autogluon) (4.5.4.60)
Requirement already satisfied: portalocker in /opt/conda/lib/python3.7/site-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.6.1->autogluon) (2.6.0)
Requirement already satisfied: pydantic~=1.7 in /opt/conda/lib/python3.7/site-packages (from gluonts~=0.11.0->autogluon.timeseries[all]==0.6.1->autogluon) (1.8.2)
Requirement already satisfied: typing-extensions~=4.0 in /opt/conda/lib/python3.7/site-packages (from gluonts~=0.11.0->autogluon.timeseries[all]==0.6.1->autogluon) (4.1.1)
Requirement already satisfied: py4j in /opt/conda/lib/python3.7/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==0.6.1->autogluon) (0.10.9.7)
Requirement already satisfied: future in /opt/conda/lib/python3.7/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==0.6.1->autogluon) (0.18.2)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema<=4.8.0->autogluon.multimodal==0.6.1->autogluon) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema<=4.8.0->autogluon.multimodal==0.6.1->autogluon) (0.18.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema<=4.8.0->autogluon.multimodal==0.6.1->autogluon) (5.10.2)
Requirement already satisfied: wheel in /opt/conda/lib/python3.7/site-packages (from lightgbm<3.4,>=3.3->autogluon.tabular[all]==0.6.1->autogluon) (0.37.1)
Requirement already satisfied: decorator>=4.3.0 in /opt/conda/lib/python3.7/site-packages (from networkx<3.0,>=2.3->autogluon.tabular[all]==0.6.1->autogluon) (5.1.1)
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.7/site-packages (from nltk<4.0.0,>=3.4.5->autogluon.multimodal==0.6.1->autogluon) (2021.11.10)
Collecting typish>=1.7.0
  Downloading typish-1.9.3-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 kB 3.3 MB/s eta 0:00:00
Collecting antlr4-python3-runtime==4.8
  Downloading antlr4-python3-runtime-4.8.tar.gz (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.4/112.4 kB 9.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: colorama in /opt/conda/lib/python3.7/site-packages (from openmim<=0.2.1,>0.1.5->autogluon.multimodal==0.6.1->autogluon) (0.4.6)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.7/site-packages (from openmim<=0.2.1,>0.1.5->autogluon.multimodal==0.6.1->autogluon) (0.9.0)
Requirement already satisfied: rich in /opt/conda/lib/python3.7/site-packages (from openmim<=0.2.1,>0.1.5->autogluon.multimodal==0.6.1->autogluon) (12.6.0)
Collecting model-index
  Downloading model_index-0.1.11-py3-none-any.whl (34 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas!=1.4.0,<1.6,>=1.2.5->autogluon.core[all]==0.6.1->autogluon) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas!=1.4.0,<1.6,>=1.2.5->autogluon.core[all]==0.6.1->autogluon) (2022.1)
Requirement already satisfied: Cython!=0.29.18,>=0.29 in /opt/conda/lib/python3.7/site-packages (from pmdarima~=1.8.2->autogluon.timeseries[all]==0.6.1->autogluon) (0.29.32)
Requirement already satisfied: urllib3 in /opt/conda/lib/python3.7/site-packages (from pmdarima~=1.8.2->autogluon.timeseries[all]==0.6.1->autogluon) (1.26.13)
Collecting pyDeprecate>=0.3.1
  Downloading pyDeprecate-0.3.2-py3-none-any.whl (10 kB)
Collecting tensorboard>=2.9.1
  Downloading tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 23.5 MB/s eta 0:00:0000:0100:01
Collecting grpcio<=1.43.0,>=1.32.0
  Downloading grpcio-1.43.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 18.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: virtualenv in /opt/conda/lib/python3.7/site-packages (from ray[tune]<2.1,>=2.0->autogluon.core[all]==0.6.1->autogluon) (20.15.1)
Collecting click>=6.6
  Downloading click-8.0.4-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 kB 8.6 MB/s eta 0:00:00
Requirement already satisfied: filelock in /opt/conda/lib/python3.7/site-packages (from ray[tune]<2.1,>=2.0->autogluon.core[all]==0.6.1->autogluon) (3.7.1)

In [62]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [68]:
train.dtypes

MedInc               float64
HouseAge             float64
AveRooms             float64
AveBedrms            float64
Population           float64
AveOccup             float64
Latitude             float64
Longitude            float64
MedHouseVal          float64
is_generated           int64
exp_latlon1          float64
exp_latlon2          float64
pca_lat              float64
pca_lon              float64
rot_15_x             float64
rot_15_y             float64
rot_30_x             float64
rot_30_y             float64
rot_45_x             float64
rot_45_y             float64
place                  int64
dist_Sac             float64
dist_SF              float64
dist_SJ              float64
dist_LA              float64
dist_SD              float64
dist_nearest_city    float64
dist_to_coast        float64
dtype: object

In [69]:
train["place"] = train["place"].astype("category")

In [81]:
# --- Launching a TabularPredictor ---

label = 'MedHouseVal'
eval_metric = 'root_mean_squared_error'
preset = 'best_quality'

#ignored_columns  = ["Population","AveBedrms","Latitude","pca_lat","Longitude","rot_15_y","dist_Sac","dist_SJ","rot_30_y","is_generated","rot_30_x","dist_SD","exp_latlon1","dist_SF","rot_15_x"]

predictor = TabularPredictor(label = label,
                             eval_metric = eval_metric,
                             #learner_kwargs = { 'ignored_columns' : ignored_columns }, # For faster feature_importance permutation
                             ).fit(train,
                                   presets = preset,
                                   #hyperparameters = 'light', # Fast research / simplicity of search settings
                                   time_limit = 1 * 3600,
                                   verbosity = 3)

results = predictor.fit_summary()

No path specified. Models will be saved in: "AutogluonModels/ag-20230108_123823/"
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'auto_stack': True, 'verbosity': 3}
Full kwargs:
{'_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': None,
 'auto_stack': True,
 'calibrate': 'auto',
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'keep_only_best': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': None,
 'pseudo_data': None,
 'refit_full': False,
 'save_space': False,
 'set_best_to_refit_full': False,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=20
Saving AutogluonModels/ag-20230108_123823/learner.pkl
Saving AutogluonModels/ag-20230108_123823/predictor.pkl
Beginning AutoGluon training ... Time limit = 3600s
AutoGluon will save models to "AutogluonModels/ag-20230108_123823/"
AutoGluon Version:  0.6.1
Python Version:     3.7.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Dec 10 10:12:26 UTC 2022
Train Data Rows:    57777
Train Data Columns: 27
Label Column: MedHouseVal
Preprocessing data ...
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (5.00001, 0.14999, 2.07575, 1.15693)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    28763.5 MB
	Train Data (Original)  Memory Usage: 12.08 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('category', 'category') :  1 | ['place']
				('float64', 'float')     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int64', 'int')         :  1 | ['is_generated']
			Types of features in original data (raw dtype, special dtypes):
				('category', []) :  1 | ['place']
				('float', [])    : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', [])      :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.1s = Fit runtime
			27 features in original data used to generate 27 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.0s = Fit runtime
			27 features in original data used to generate 27 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.0s = Fit runtime
			26 features in original data used to generate 26 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 1 | ['place']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 1 | ['place']
				0.0s = Fit runtime
				1 features in original data used to generate 1 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('category', []) : 1 | ['place']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 1 | ['place']
			0.0s = Fit runtime
			1 features in original data used to generate 1 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.1s = Fit runtime
			27 features in original data used to generate 27 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('category', 'category') :  1 | ['place']
		('float64', 'float')     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
		('int64', 'int')         :  1 | ['is_generated']
	Types of features in original data (raw dtype, special dtypes):
		('category', []) :  1 | ['place']
		('float', [])    : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
		('int', [])      :  1 | ['is_generated']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  1 | ['place']
		('float64', 'float')     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
		('int8', 'int')          :  1 | ['is_generated']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  1 | ['place']
		('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
		('int', ['bool']) :  1 | ['is_generated']
	0.4s = Fit runtime
	27 features in original data used to generate 27 features in processed data.
	Train Data (Processed) Memory Usage: 11.67 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.5s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Saving AutogluonModels/ag-20230108_123823/learner.pkl
Saving AutogluonModels/ag-20230108_123823/utils/data/X.pkl
Saving AutogluonModels/ag-20230108_123823/utils/data/y.pkl
AutoGluon will fit 2 stack levels (L1 to L2) ...
Model configs that will be trained (in order):
	KNeighborsUnif_BAG_L1: 	{'weights': 'uniform', 'ag_args': {'valid_stacker': False, 'name_suffix': 'Unif', 'model_type': <class 'autogluon.tabular.models.knn.knn_model.KNNModel'>, 'priority': 100}, 'ag_args_ensemble': {'use_child_oof': True}}
	KNeighborsDist_BAG_L1: 	{'weights': 'distance', 'ag_args': {'valid_stacker': False, 'name_suffix': 'Dist', 'model_type': <class 'autogluon.tabular.models.knn.knn_model.KNNModel'>, 'priority': 100}, 'ag_args_ensemble': {'use_child_oof': True}}
	LightGBMXT_BAG_L1: 	{'extra_trees': True, 'ag_args': {'name_suffix': 'XT', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
	LightGBM_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
	RandomForestMSE_BAG_L1: 	{'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile'], 'model_type': <class 'autogluon.tabular.models.rf.rf_model.RFModel'>, 'priority': 80}, 'ag_args_ensemble': {'use_child_oof': True}}
	CatBoost_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}}
	ExtraTreesMSE_BAG_L1: 	{'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile'], 'model_type': <class 'autogluon.tabular.models.xt.xt_model.XTModel'>, 'priority': 60}, 'ag_args_ensemble': {'use_child_oof': True}}
	NeuralNetFastAI_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.fastainn.tabular_nn_fastai.NNFastAiTabularModel'>, 'priority': 50}}
	XGBoost_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}}
	NeuralNetTorch_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.tabular_nn.torch.tabular_nn_torch.TabularNeuralNetTorchModel'>, 'priority': 25}}
	LightGBMLarge_BAG_L1: 	{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 5, 'ag_args': {'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'name_suffix': 'Large', 'hyperparameter_tune_kwargs': None, 'priority': 0}}
Fitting 11 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 2399.06s of the 3599.48s of remaining time.
	Fitting KNeighborsUnif_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/KNeighborsUnif_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/KNeighborsUnif_BAG_L1/utils/model_template.pkl
	Using sklearnex KNN backend...
	0.02s 	= Train Time (Using 10000/57777 rows) (2399.03s remaining time)
	0.01s 	= Train Time (Using 20000/57777 rows) (2399.02s remaining time)
	0.02s 	= Train Time (Using 57777/57777 rows) (2399.0s remaining time)
	5.65s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving AutogluonModels/ag-20230108_123823/models/KNeighborsUnif_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/KNeighborsUnif_BAG_L1/model.pkl
	-0.6978	 = Validation score   (-root_mean_squared_error)
	0.13s	 = Training   runtime
	4.09s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 2394.69s of the 3595.11s of remaining time.
	Fitting KNeighborsDist_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/KNeighborsDist_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/KNeighborsDist_BAG_L1/utils/model_template.pkl
	Using sklearnex KNN backend...
	0.01s 	= Train Time (Using 10000/57777 rows) (2394.67s remaining time)
	0.01s 	= Train Time (Using 20000/57777 rows) (2394.66s remaining time)
	0.02s 	= Train Time (Using 57777/57777 rows) (2394.63s remaining time)
	5.96s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving AutogluonModels/ag-20230108_123823/models/KNeighborsDist_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/KNeighborsDist_BAG_L1/model.pkl
	-0.7382	 = Validation score   (-root_mean_squared_error)
	0.11s	 = Training   runtime
	4.17s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2390.26s of the 3590.68s of remaining time.
	Fitting LightGBMXT_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L1/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L1/model.pkl
	-0.5111	 = Validation score   (-root_mean_squared_error)
	464.06s	 = Training   runtime
	64.39s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1645.66s of the 2846.07s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L1/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L1/model.pkl
	-0.5137	 = Validation score   (-root_mean_squared_error)
	217.26s	 = Training   runtime
	21.68s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 1411.17s of the 2611.59s of remaining time.
	Fitting RandomForestMSE_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L1/utils/model_template.pkl
	22.19s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L1/model.pkl
	-0.532	 = Validation score   (-root_mean_squared_error)
	496.86s	 = Training   runtime
	3.53s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: CatBoost_BAG_L1 ... Training model for up to 909.7s of the 2110.11s of remaining time.
	Fitting CatBoost_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/CatBoost_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/CatBoost_BAG_L1/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_123823/models/CatBoost_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/CatBoost_BAG_L1/model.pkl
	-0.5131	 = Validation score   (-root_mean_squared_error)
	745.73s	 = Training   runtime
	1.81s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 147.64s of the 1348.05s of remaining time.
	Fitting ExtraTreesMSE_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/ExtraTreesMSE_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/ExtraTreesMSE_BAG_L1/utils/model_template.pkl
	26.3s	= Estimated out-of-fold prediction time...
	`use_child_oof` was specified for this model. It will function similarly to a bagged model, but will only fit one child model.
Saving AutogluonModels/ag-20230108_123823/models/ExtraTreesMSE_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/ExtraTreesMSE_BAG_L1/model.pkl
	-0.5187	 = Validation score   (-root_mean_squared_error)
	100.66s	 = Training   runtime
	3.26s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 41.62s of the 1242.04s of remaining time.
	Fitting NeuralNetFastAI_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/NeuralNetFastAI_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/NeuralNetFastAI_BAG_L1/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_123823/models/NeuralNetFastAI_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/NeuralNetFastAI_BAG_L1/model.pkl
	-0.6353	 = Validation score   (-root_mean_squared_error)
	72.44s	 = Training   runtime
	7.17s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Skipping XGBoost_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Skipping NeuralNetTorch_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Skipping LightGBMLarge_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Not enough time left to finish repeated k-fold bagging, stopping early ...
Completed 1/20 k-fold bagging repeats ...
Loading: AutogluonModels/ag-20230108_123823/models/KNeighborsUnif_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/KNeighborsDist_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/CatBoost_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/ExtraTreesMSE_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_123823/models/NeuralNetFastAI_BAG_L1/utils/oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 1151.43s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_123823/models/WeightedEnsemble_L2/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_123823/models/WeightedEnsemble_L2/utils/model_template.pkl
Ensemble size: 75
Ensemble weights:
[0.05333333 0.02666667 0.38666667 0.2        0.         0.12
 0.21333333 0.        ]
	0.4s	= Estimated out-of-fold prediction time...
Saving AutogluonModels/ag-20230108_123823/models/WeightedEnsemble_L2/utils/oof.pkl
Saving AutogluonModels/ag-20230108_123823/models/WeightedEnsemble_L2/model.pkl
	-0.5046	 = Validation score   (-root_mean_squared_error)
	1.35s	 = Training   runtime
	0.0s	 = Validation runtime
Saving AutogluonModels/ag-20230108_123823/models/trainer.pkl
Model configs that will be trained (in order):
	LightGBMXT_BAG_L2: 	{'extra_trees': True, 'ag_args': {'name_suffix': 'XT', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}

*** Summary of fit() ***
Estimated performance of each model:
                     model  score_val  pred_time_val     fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      WeightedEnsemble_L3  -0.502684     121.084608  3171.824049                0.001866           0.956919            3       True         14
1        LightGBMXT_BAG_L2  -0.503849     113.663397  2180.199908                3.566422          82.959781            2       True         10
2          LightGBM_BAG_L2  -0.503886     112.441883  2166.605007                2.344908          69.364881            2       True         11
3      WeightedEnsemble_L2  -0.504632      99.402259  1529.287790                0.001977           1.346576            2       True          9
4   RandomForestMSE_BAG_L2  -0.510166     115.171412  3018.542467                5.074437         921.302341            2       True         12
5        LightGBMXT_BAG_L1  -0.511114      64.385175   464.057156               64.385175         464.057156            1       True          3
6          CatBoost_BAG_L1  -0.513128       1.809405   745.734684                1.809405         745.734684            1       True          6
7          LightGBM_BAG_L1  -0.513704      21.684633   217.256809               21.684633         217.256809            1       True          4
8     ExtraTreesMSE_BAG_L1  -0.518698       3.261606   100.656969                3.261606         100.656969            1       True          7
9   RandomForestMSE_BAG_L1  -0.532021       3.530942   496.855108                3.530942         496.855108            1       True          5
10         CatBoost_BAG_L2  -0.598763     111.570079  2142.557636                1.473104          45.317510            2       True         13
11  NeuralNetFastAI_BAG_L1  -0.635275       7.165751    72.443805                7.165751          72.443805            1       True          8
12   KNeighborsUnif_BAG_L1  -0.697754       4.092519     0.126531                4.092519           0.126531            1       True          1
13   KNeighborsDist_BAG_L1  -0.738180       4.166944     0.109066                4.166944           0.109066            1       True          2
Number of models trained: 14
Types of models trained:
{'StackerEnsembleModel_KNN', 'StackerEnsembleModel_CatBoost', 'StackerEnsembleModel_LGB', 'StackerEnsembleModel_NNFastAiTabular', 'StackerEnsembleModel_XT', 'WeightedEnsembleModel', 'StackerEnsembleModel_RF'}
Bagging used: True  (with 8 folds)
Multi-layer stack-ensembling used: True  (with 3 levels)
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', [])  :  1 | ['place']
('float', [])     : 25 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', ...]
('int', ['bool']) :  1 | ['is_generated']
Plot summary of models saved to file: AutogluonModels/ag-20230108_123823/SummaryOfModels.html
*** End of fit() summary ***

In [82]:
y_pred = predictor.predict(test)

Loading: AutogluonModels/ag-20230108_123823/models/CatBoost_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/ExtraTreesMSE_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/KNeighborsDist_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/KNeighborsUnif_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/NeuralNetFastAI_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBMXT_BAG_L2/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/LightGBM_BAG_L2/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/RandomForestMSE_BAG_L2/model.pkl
Loading: AutogluonModels/ag-20230108_123823/models/WeightedEnsemble_L3/model.pkl

In [83]:
y_pred

0        0.684733
1        1.075492
2        3.948377
3        3.209853
4        2.460941
           ...
24754    2.716174
24755    1.794602
24756    1.219339
24757    3.556829
24758    3.420027
Name: MedHouseVal, Length: 24759, dtype: float32

In [86]:
ss["MedHouseVal"] = y_pred

In [88]:
ss = ss.set_index("id")
ss

       MedHouseVal
id
37137     0.684733
37138     1.075492
37139     3.948377
37140     3.209853
37141     2.460941
...            ...
61891     2.716174
61892     1.794602
61893     1.219339
61894     3.556829
61895     3.420027

[24759 rows x 1 columns]

In [89]:
ss.to_csv("sub.csv")

In [ ]:
predictor.feature_importance(train)

In [91]:
# --- Launching a TabularPredictor ---

label = 'MedHouseVal'
eval_metric = 'root_mean_squared_error'
#preset = 'best_quality'

ignored_columns  = ["Population"] # "AveBedrms","Latitude","pca_lat","Longitude","rot_15_y","dist_Sac","dist_SJ","rot_30_y","is_generated","rot_30_x","dist_SD","exp_latlon1","dist_SF","rot_15_x"

predictor = TabularPredictor(label = label,
                             eval_metric = eval_metric,
                             learner_kwargs = { 'ignored_columns' : ignored_columns }, # For faster feature_importance permutation
                             ).fit(train,
                                   presets = preset,
                                   hyperparameters = 'light', # Fast research / simplicity of search settings
                                   time_limit = 0.21 * 3600,
                                   verbosity = 3)

results = predictor.fit_summary()

No path specified. Models will be saved in: "AutogluonModels/ag-20230108_140252/"
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'auto_stack': True, 'verbosity': 3}
Full kwargs:
{'_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': None,
 'auto_stack': True,
 'calibrate': 'auto',
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'keep_only_best': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': None,
 'pseudo_data': None,
 'refit_full': False,
 'save_space': False,
 'set_best_to_refit_full': False,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'verbosity': 3}
========================================
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=20
Saving AutogluonModels/ag-20230108_140252/learner.pkl
Saving AutogluonModels/ag-20230108_140252/predictor.pkl
Beginning AutoGluon training ... Time limit = 756.0s
AutoGluon will save models to "AutogluonModels/ag-20230108_140252/"
AutoGluon Version:  0.6.1
Python Version:     3.7.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Dec 10 10:12:26 UTC 2022
Train Data Rows:    57777
Train Data Columns: 27
Label Column: MedHouseVal
Preprocessing data ...
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (5.00001, 0.14999, 2.07575, 1.15693)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Using Feature Generators to preprocess the data ...
Dropping user-specified ignored columns: ['Population']
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    29456.6 MB
	Train Data (Original)  Memory Usage: 11.61 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('category', 'category') :  1 | ['place']
				('float64', 'float')     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int64', 'int')         :  1 | ['is_generated']
			Types of features in original data (raw dtype, special dtypes):
				('category', []) :  1 | ['place']
				('float', [])    : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', [])      :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.1s = Fit runtime
			26 features in original data used to generate 26 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.0s = Fit runtime
			26 features in original data used to generate 26 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.0s = Fit runtime
			25 features in original data used to generate 25 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 1 | ['place']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 1 | ['place']
				0.0s = Fit runtime
				1 features in original data used to generate 1 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('category', []) : 1 | ['place']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 1 | ['place']
			0.1s = Fit runtime
			1 features in original data used to generate 1 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  :  1 | ['place']
				('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
				('int', ['bool']) :  1 | ['is_generated']
			0.1s = Fit runtime
			26 features in original data used to generate 26 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('category', 'category') :  1 | ['place']
		('float64', 'float')     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
		('int64', 'int')         :  1 | ['is_generated']
	Types of features in original data (raw dtype, special dtypes):
		('category', []) :  1 | ['place']
		('float', [])    : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
		('int', [])      :  1 | ['is_generated']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') :  1 | ['place']
		('float64', 'float')     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
		('int8', 'int')          :  1 | ['is_generated']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  1 | ['place']
		('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
		('int', ['bool']) :  1 | ['is_generated']
	0.4s = Fit runtime
	26 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 11.21 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.51s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Saving AutogluonModels/ag-20230108_140252/learner.pkl
Saving AutogluonModels/ag-20230108_140252/utils/data/X.pkl
Saving AutogluonModels/ag-20230108_140252/utils/data/y.pkl
AutoGluon will fit 2 stack levels (L1 to L2) ...
Model configs that will be trained (in order):
	LightGBMXT_BAG_L1: 	{'extra_trees': True, 'ag_args': {'name_suffix': 'XT', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
	LightGBM_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
	RandomForestMSE_BAG_L1: 	{'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile'], 'model_type': <class 'autogluon.tabular.models.rf.rf_model.RFModel'>, 'priority': 80}, 'ag_args_ensemble': {'use_child_oof': True}}
	CatBoost_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}}
	ExtraTreesMSE_BAG_L1: 	{'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile'], 'model_type': <class 'autogluon.tabular.models.xt.xt_model.XTModel'>, 'priority': 60}, 'ag_args_ensemble': {'use_child_oof': True}}
	NeuralNetFastAI_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.fastainn.tabular_nn_fastai.NNFastAiTabularModel'>, 'priority': 50}}
	XGBoost_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}}
	NeuralNetTorch_BAG_L1: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.tabular_nn.torch.tabular_nn_torch.TabularNeuralNetTorchModel'>, 'priority': 25}}
	LightGBMLarge_BAG_L1: 	{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 5, 'ag_args': {'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'name_suffix': 'Large', 'hyperparameter_tune_kwargs': None, 'priority': 0}}
Fitting 9 L1 models ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 503.53s of the 755.46s of remaining time.
	Fitting LightGBMXT_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/model.pkl
	-0.5118	 = Validation score   (-root_mean_squared_error)
	407.07s	 = Training   runtime
	69.98s	 = Validation runtime
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Fitting model: LightGBM_BAG_L1 ... Training model for up to 75.55s of the 327.48s of remaining time.
	Fitting LightGBM_BAG_L1 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/utils/oof.pkl
Saving AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/model.pkl
	-0.5185	 = Validation score   (-root_mean_squared_error)
	90.54s	 = Training   runtime
	7.97s	 = Validation runtime
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping RandomForestMSE_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping CatBoost_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping ExtraTreesMSE_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping NeuralNetFastAI_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping XGBoost_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping NeuralNetTorch_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping LightGBMLarge_BAG_L1 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Not enough time left to finish repeated k-fold bagging, stopping early ...
Completed 1/20 k-fold bagging repeats ...
Loading: AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/utils/oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L2: 	{'ag_args': {'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 217.43s of remaining time.
	Fitting WeightedEnsemble_L2 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L2/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L2/utils/model_template.pkl
Ensemble size: 10
Ensemble weights:
[0.7 0.3]
	0.18s	= Estimated out-of-fold prediction time...
Saving AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L2/utils/oof.pkl
Saving AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L2/model.pkl
	-0.5103	 = Validation score   (-root_mean_squared_error)
	0.69s	 = Training   runtime
	0.0s	 = Validation runtime
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Model configs that will be trained (in order):
	LightGBMXT_BAG_L2: 	{'extra_trees': True, 'ag_args': {'name_suffix': 'XT', 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
	LightGBM_BAG_L2: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
	RandomForestMSE_BAG_L2: 	{'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile'], 'model_type': <class 'autogluon.tabular.models.rf.rf_model.RFModel'>, 'priority': 80}, 'ag_args_ensemble': {'use_child_oof': True}}
	CatBoost_BAG_L2: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.catboost.catboost_model.CatBoostModel'>, 'priority': 70}}
	ExtraTreesMSE_BAG_L2: 	{'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile'], 'model_type': <class 'autogluon.tabular.models.xt.xt_model.XTModel'>, 'priority': 60}, 'ag_args_ensemble': {'use_child_oof': True}}
	NeuralNetFastAI_BAG_L2: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.fastainn.tabular_nn_fastai.NNFastAiTabularModel'>, 'priority': 50}}
	XGBoost_BAG_L2: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.xgboost.xgboost_model.XGBoostModel'>, 'priority': 40}}
	NeuralNetTorch_BAG_L2: 	{'ag_args': {'model_type': <class 'autogluon.tabular.models.tabular_nn.torch.tabular_nn_torch.TabularNeuralNetTorchModel'>, 'priority': 25}}
	LightGBMLarge_BAG_L2: 	{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 5, 'ag_args': {'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'name_suffix': 'Large', 'hyperparameter_tune_kwargs': None, 'priority': 0}}
Fitting 9 L2 models ...
Loading: AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/utils/oof.pkl
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 216.71s of the 216.68s of remaining time.
	Fitting LightGBMXT_BAG_L2 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L2/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L2/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L2/utils/oof.pkl
Saving AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L2/model.pkl
	-0.5129	 = Validation score   (-root_mean_squared_error)
	74.03s	 = Training   runtime
	5.15s	 = Validation runtime
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Fitting model: LightGBM_BAG_L2 ... Training model for up to 124.15s of the 124.12s of remaining time.
	Fitting LightGBM_BAG_L2 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L2/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L2/utils/model_template.pkl
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Saving AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L2/utils/oof.pkl
Saving AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L2/model.pkl
	-0.5122	 = Validation score   (-root_mean_squared_error)
	58.62s	 = Training   runtime
	3.29s	 = Validation runtime
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 48.38s of the 48.35s of remaining time.
	Fitting RandomForestMSE_BAG_L2 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/RandomForestMSE_BAG_L2/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/RandomForestMSE_BAG_L2/utils/model_template.pkl
	11.35s	= Estimated out-of-fold prediction time...
	Not enough time to generate out-of-fold predictions for model. Estimated time required was 11.35s compared to 10s of available time.
	Time limit exceeded... Skipping RandomForestMSE_BAG_L2.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping CatBoost_BAG_L2 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping ExtraTreesMSE_BAG_L2 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping NeuralNetFastAI_BAG_L2 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping XGBoost_BAG_L2 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping NeuralNetTorch_BAG_L2 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Skipping LightGBMLarge_BAG_L2 due to lack of time remaining.
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Not enough time left to finish repeated k-fold bagging, stopping early ...
Completed 1/20 k-fold bagging repeats ...
Loading: AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L2/utils/oof.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L2/utils/oof.pkl
Model configs that will be trained (in order):
	WeightedEnsemble_L3: 	{'ag_args': {'valid_base': False, 'name_bag_suffix': '', 'model_type': <class 'autogluon.core.models.greedy_ensemble.greedy_weighted_ensemble_model.GreedyWeightedEnsembleModel'>, 'priority': 0}, 'ag_args_ensemble': {'save_bag_folds': True}}
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the -384.12s of remaining time.
	Fitting WeightedEnsemble_L3 with 'num_gpus': 0, 'num_cpus': 4
Saving AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L3/utils/model_template.pkl
Loading: AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L3/utils/model_template.pkl
Ensemble size: 5
Ensemble weights:
[0.4 0.6]
	0.17s	= Estimated out-of-fold prediction time...
Saving AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L3/utils/oof.pkl
Saving AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L3/model.pkl
	-0.5116	 = Validation score   (-root_mean_squared_error)
	0.5s	 = Training   runtime
	0.0s	 = Validation runtime
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl
Saving AutogluonModels/ag-20230108_140252/models/trainer.pkl

*** Summary of fit() ***
Estimated performance of each model:
                 model  score_val  pred_time_val    fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0  WeightedEnsemble_L2  -0.510254      77.958217  498.308474                0.001755           0.691870            2       True          3
1  WeightedEnsemble_L3  -0.511561      86.398510  630.768070                0.001887           0.500617            3       True          6
2    LightGBMXT_BAG_L1  -0.511838      69.981508  407.071790               69.981508         407.071790            1       True          1
3      LightGBM_BAG_L2  -0.512224      81.248441  556.239863                3.291978          58.623260            2       True          5
4    LightGBMXT_BAG_L2  -0.512948      83.104645  571.644194                5.148182          74.027591            2       True          4
5      LightGBM_BAG_L1  -0.518455       7.974954   90.544814                7.974954          90.544814            1       True          2
Number of models trained: 6
Types of models trained:
{'StackerEnsembleModel_LGB', 'WeightedEnsembleModel'}
Bagging used: True  (with 8 folds)
Multi-layer stack-ensembling used: True  (with 3 levels)
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', [])  :  1 | ['place']
('float', [])     : 24 | ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', ...]
('int', ['bool']) :  1 | ['is_generated']
Plot summary of models saved to file: AutogluonModels/ag-20230108_140252/SummaryOfModels.html
*** End of fit() summary ***

In [98]:
y_pred = predictor.predict(test)

Loading: AutogluonModels/ag-20230108_140252/models/LightGBMXT_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_140252/models/LightGBM_BAG_L1/model.pkl
Loading: AutogluonModels/ag-20230108_140252/models/WeightedEnsemble_L2/model.pkl

In [109]:
y_pred = pd.DataFrame(y_pred)

In [115]:
y_pred["MedHouseVal"]

0        0.657503
1        1.043892
2        4.101843
3        3.260886
4        2.508345
           ...
24754    2.646386
24755    1.876054
24756    1.212681
24757    3.671331
24758    3.598445
Name: MedHouseVal, Length: 24759, dtype: float32

In [117]:
ss = ss.drop(columns=["MedHouseVal"])

In [118]:
ss

Empty DataFrame
Columns: []
Index: [37137, 37138, 37139, 37140, 37141, 37142, 37143, 37144, 37145, 37146, 37147, 37148, 37149, 37150, 37151, 37152, 37153, 37154, 37155, 37156, 37157, 37158, 37159, 37160, 37161, 37162, 37163, 37164, 37165, 37166, 37167, 37168, 37169, 37170, 37171, 37172, 37173, 37174, 37175, 37176, 37177, 37178, 37179, 37180, 37181, 37182, 37183, 37184, 37185, 37186, 37187, 37188, 37189, 37190, 37191, 37192, 37193, 37194, 37195, 37196, 37197, 37198, 37199, 37200, 37201, 37202, 37203, 37204, 37205, 37206, 37207, 37208, 37209, 37210, 37211, 37212, 37213, 37214, 37215, 37216, 37217, 37218, 37219, 37220, 37221, 37222, 37223, 37224, 37225, 37226, 37227, 37228, 37229, 37230, 37231, 37232, 37233, 37234, 37235, 37236, ...]

[24759 rows x 0 columns]

In [122]:
y_pred.index = y_pred.index+37137

In [125]:
y_pred.index = y_pred.index.rename("id")

In [128]:
y_pred.to_csv("sub_3.csv")

# Test de LightAutoML :

In [129]:
%%capture
!pip install -U lightautoml

In [130]:
# LightAutoML presets, task and report generation
from lightautoml.automl.presets.tabular_presets import TabularAutoML, TabularUtilizedAutoML
from lightautoml.tasks import Task
from lightautoml.report.report_deco import ReportDeco

pd.set_option('display.max_columns', None)

In [131]:
N_THREADS = 4
RANDOM_STATE = 51
# TEST_SIZE = 0.2
TIMEOUT = 1 * 60
TARGET_NAME = 'MedHouseVal'
N_FOLDS = 10

In [132]:
task = Task(name = 'reg',
#             loss = 'mse',
#             metric = 'mse'
           )

In [137]:
roles = {'target': TARGET_NAME,
#          'drop': ['id']
         }

In [138]:
automl = TabularAutoML(task = task,
                       
                       timeout = TIMEOUT,
                       cpu_limit = N_THREADS,
                       reader_params = {'n_jobs': N_THREADS, 'random_state': RANDOM_STATE},
                       general_params = {'use_algos': [['linear_l2', 'lgb', 'cb', 'lgb_tuned','cb_tuned']]}
                      )

In [139]:
oof_pred = automl.fit_predict(train, roles=roles, verbose=5)
print(f'oof_pred:\n{oof_pred}\nShape = {oof_pred.shape}')

[14:38:12] Stdout logging level is DEBUG.
[14:38:12] Copying TaskTimer may affect the parent PipelineTimer, so copy will create new unlimited TaskTimer
[14:38:12] Task: reg

[14:38:12] Start automl preset with listed constraints:
[14:38:12] - time: 60.00 seconds
[14:38:12] - CPU: 4 cores
[14:38:12] - memory: 16 GB

[14:38:12] Train data shape: (57777, 28)

[14:38:47] Feats was rejected during automatic roles guess: []
[14:38:47] Layer 1 train process start. Time left 25.14 secs
[14:38:52] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[14:38:52] Training params: {'tol': 1e-06, 'max_iter': 100, 'cs': [1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000], 'early_stopping': 2, 'categorical_idx': [51], 'embed_sizes': array([16], dtype=int32), 'data_size': 52}
[14:38:52] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[14:38:53] Linear model: C = 1e-05 score = -0.42448004392285715
[14:38:53] Linear model: C = 5e-05 score = -0.39200518127859973
[14:38:53] Linear model: C = 0.0001 score = -0.38729116349355575
[14:38:54] Linear model: C = 0.0005 score = -0.38264537913979496
[14:38:54] Linear model: C = 0.001 score = -0.3816588476633714
[14:38:54] Linear model: C = 0.005 score = -0.3802932445012435
[14:38:54] Linear model: C = 0.01 score = -0.3802893722919889
[14:38:54] Linear model: C = 0.05 score = -0.38029835426559416
[14:38:55] Linear model: C = 0.1 score = -0.3802904040419538
[14:38:55] Time limit exceeded after calculating fold 0

[14:38:55] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -0.3802893722919889
[14:38:55] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[14:38:55] Time left 17.53 secs

[14:38:56] Training until validation scores don't improve for 200 rounds
[14:40:35] [100]	valid's l2: 0.311398
[14:42:10] [200]	valid's l2: 0.284821
[14:43:40] [300]	valid's l2: 0.277105
[14:45:11] [400]	valid's l2: 0.273404
[14:46:39] [500]	valid's l2: 0.27063
[14:48:06] [600]	valid's l2: 0.268928
[14:49:30] [700]	valid's l2: 0.267854
[14:50:59] [800]	valid's l2: 0.267062
[14:52:25] [900]	valid's l2: 0.266042
[14:53:52] [1000]	valid's l2: 0.26568
[14:55:18] [1100]	valid's l2: 0.265413
[14:56:43] [1200]	valid's l2: 0.265037
[14:56:43] Did not meet early stopping. Best iteration is:
[1197]	valid's l2: 0.265032
[14:56:46] Selector_LightGBM fitting and predicting completed
[14:56:52] Start fitting Lvl_0_Pipe_1_Mod_0_LightGBM ...
[14:56:52] Training params: {'task': 'train', 'learning_rate': 0.03, 'num_leaves': 32, 'feature_fraction': 0.9, 'bagging_fraction': 0.9, 'bagging_freq': 1, 'max_depth': -1, 'verbosity': -1, 'reg_alpha': 1, 'reg_lambda': 0.0, 'min_split_gain': 0.0, 'zero_as_missing': False, 'num_threads': 4, 'max_bin': 255, 'min_data_in_bin': 3, 'num_trees': 1200, 'early_stopping_rounds': 200, 'random_state': 42}
[14:56:52] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_LightGBM =====
[14:56:54] Training until validation scores don't improve for 200 rounds
[14:58:32] [100]	valid's l2: 0.311045
[15:00:09] [200]	valid's l2: 0.286205
[15:01:39] [300]	valid's l2: 0.280632
[15:03:09] [400]	valid's l2: 0.277743
[15:04:37] [500]	valid's l2: 0.276056
[15:06:05] [600]	valid's l2: 0.274587
[15:07:32] [700]	valid's l2: 0.273755
[15:08:59] [800]	valid's l2: 0.273036
[15:10:29] [900]	valid's l2: 0.272504
[15:11:56] [1000]	valid's l2: 0.271968
[15:13:23] [1100]	valid's l2: 0.271758
[15:14:50] [1200]	valid's l2: 0.271479
[15:14:50] Did not meet early stopping. Best iteration is:
[1200]	valid's l2: 0.271479
[15:14:53] Time limit exceeded after calculating fold 0

[15:14:53] Fitting Lvl_0_Pipe_1_Mod_0_LightGBM finished. score = -0.2714790089248549
[15:14:53] Lvl_0_Pipe_1_Mod_0_LightGBM fitting and predicting completed
[15:14:53] Time left -2140.57 secs

[15:14:53] Time limit exceeded. Last level models will be blended and unused pipelines will be pruned.

[15:14:53] Layer 1 training completed.

[15:14:53] Blending: optimization starts with equal weights and score -0.2955361817712418
[15:14:53] Blending: iteration 0: score = -0.2711530028829538, weights = [0.05181924 0.94818074]
[15:14:53] Blending: iteration 1: score = -0.2711530028829538, weights = [0.05181924 0.94818074]
[15:14:53] Blending: no score update. Terminated

[15:14:53] Automl preset training completed in 2200.71 seconds

[15:14:53] Model description:
Final prediction for new objects (level 0) =
	 0.05182 * (1 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.94818 * (1 averaged models Lvl_0_Pipe_1_Mod_0_LightGBM)

oof_pred:
array([[       nan],
       [1.4549185 ],
       [       nan],
       ...,
       [0.90995353],
       [       nan],
       [1.0360521 ]], dtype=float32)
Shape = (57777, 1)

In [140]:
oof_pred_train = oof_pred.data[:len(train), 0]

In [142]:
%%time

test_pred = automl.predict(test)
print(f'Prediction for test data:\n{test_pred}\nShape = {test_pred.shape}')

Prediction for test data:
array([[0.72485113],
       [0.9538561 ],
       [3.9692798 ],
       ...,
       [1.1748868 ],
       [3.855534  ],
       [3.3693113 ]], dtype=float32)
Shape = (24759, 1)
CPU times: user 5.36 s, sys: 45 ms, total: 5.4 s
Wall time: 5.69 s

In [143]:
ss[TARGET_NAME] = test_pred.data[:, 0]

In [144]:
ss

       MedHouseVal
id
37137     0.724851
37138     0.953856
37139     3.969280
37140     3.114240
37141     2.463113
...            ...
61891     2.709436
61892     1.977542
61893     1.174887
61894     3.855534
61895     3.369311

[24759 rows x 1 columns]

In [147]:
ss.to_csv('lightautoml.csv')

---

In [149]:
X = train.copy()
y = train.pop('MedHouseVal')

from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 51)

In [150]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error

def predict_and_acc(model):
        model = model()
        model.fit(X_train, y_train)
        predict = model.predict(X_test)
        cvs = cross_val_score(model, X, y, cv = 4)
        print(f'mean_squared_error {str(model)} is {float(mean_squared_error(y_test, predict))}')
        print(f'The cross validation of {str(model)} is:{cvs} with mean of {cvs.mean()}')

In [151]:
predict_and_acc(RandomForestRegressor)

KeyboardInterrupt:

In [ ]:
predict_and_acc(LGBMRegressor)

In [ ]:
predict_and_acc(CatBoostRegressor)

In [163]:
#object_cols = [col for col in train.columns if train[col].dtype == 'object' or train[col].dtype == 'category']
#train[object_cols] = train[object_cols].astype('category')

In [164]:
train["place"]=train["place"].dty(int)

AttributeError: 'Series' object has no attribute 'as_type'

In [156]:
model = CatBoostRegressor(iterations = 150000)
model.fit(X_train, y_train)
predict = model.predict(X_test)
cvs = cross_val_score(model, X, y, cv = 10)
print(f'mean_squared_error {str(model)} is {float(mean_squared_error(y_test, predict))}')
print(f'The cross validation of {str(model)} is:{cvs} with mean of {cvs.mean()}')

CatBoostError: features data: pandas.DataFrame column 'place' has dtype 'category' but is not in  cat_features list

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score
from catboost import CatBoostRegressor

def predict_and_acc(model, verbose=None):
    if verbose == None:
        model = model()
        model.fit(X_train, y_train)
        predict = model.predict(X_test)
        cvs = cross_val_score(model, X, y, cv=4)
        print(f'The accuracy score of {str(model)} is {float(_score(y_test, predict))}')
        print(f'The cross validation of {str(model)} is:{cvs} with mean of {cvs.mean()}')
    else:
        model = model(verbose=verbose)
        model.fit(X_train, y_train)
        predict = model.predict(X_test)
        cvs = cross_val_score(model, X, y, cv=4)
        print(f'The accuracy score of {str(model)} is {float(accuracy_score(y_test, predict))}')
        print(f'The cross validation of {str(model)} is:{cvs} with mean of {cvs.mean()}')

In [ ]:
predict_and_acc(CatBoostRegressor(iterations = 150000), verbose=15000)

In [ ]:
time_limit = 0.1 * 3600  # for quick demonstration only, you should set this to longest time you are willing to wait (in seconds)
metric = 'roc_auc'  # specify your evaluation metric here
predictor = TabularPredictor(label, eval_metric=metric).fit(train_data, time_limit=time_limit, presets='best_quality', )
predictor.leaderboard(test_data, silent=True)

In [ ]:
predictor = TabularPredictor(label=label, eval_metric=metric).fit(train_data,
    num_bag_folds=5, num_bag_sets=1, num_stack_levels=1,
    hyperparameters = {'NN_TORCH': {'num_epochs': 2}, 'GBM': {'num_boost_round': 20}},  # last  argument is just for quick demo here, omit it in real applications
)

In [ ]:
test_acc = predictor.evaluate(test_data)

KeyError: "['id'] not found in axis"

In [ ]:
# Après modélisation réaliser un ensemble de poids exponentiel pour calculer le poids combinatoire de chaque modèle
# Lors du split, approche temporalepossible séparation du jeu de donnée et des modèles prédictifs en subdivisions découpées par rapport au 
# Créer variable categ N, NE, NO, O, E, S, SE, SO?